name: Common Continuous Integration tasks

on:
  workflow_call:

permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write
  # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
  id-token: write

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@5f11437c716059f30c635f90055060e4ef8b31a0 # 0.28.0
    with:
      linter-env: |
        FILTER_REGEX_EXCLUDE=packages/theme/lib/**/*,packages/docs/build/**/*
        VALIDATE_TYPESCRIPT_ES=false
        VALIDATE_JAVASCRIPT_ES=false
        VALIDATE_TSX=false
        VALIDATE_CSS=false

  nodejs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@23af54bc615d657aa9c13c472ae701445c1811a6 # 0.17.1
    with:
      build: |
        {
          "artifact": ["packages/theme/lib", "packages/docs/build"]
        }

  package-theme:
    name: Package and verify Docusaurus theme
    needs: [linter, nodejs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@23af54bc615d657aa9c13c472ae701445c1811a6 # 0.17.1
      - name: Download build artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build
          path: /

      - name: Create package tarball
        working-directory: packages/theme
        run: |
          # When running for tags, update package.json version to match tag name
          if [ "${{ github.ref_type }}" == "tag" ] && [ -n "${{ github.ref_name }}" ]; then
            echo "Updating package version to match tag name: ${{ github.ref_name }}"
            npm version "${{ github.ref_name }}" --no-git-tag-version --no-workspaces-update
          fi

          npm pack --pack-destination ${{ runner.temp }}/

      - name: Install package in the docs package to verify
        working-directory: packages/docs
        run: |
          npm uninstall @hoverkraft/docusaurus-theme || true
          npm install ${{ runner.temp }}/hoverkraft-docusaurus-theme-*.tgz
          npm run build

      - name: Upload package tarball
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: package-tarball
          path: ${{ runner.temp }}/hoverkraft-docusaurus-theme-*.tgz
